language: python
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
    - python: 3.6
    - python: 3.5
install:
  - pip install pytest matplotlib
  - pip install .
script:
  - py.test
